package com.callbackdev.saldo.core.domain.model

import java.math.BigDecimal
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneOffset
import java.util.Currency

/**
 * A single ledger movement.
 *
 * ### Amount sign convention
 * [amount] is the *signed effect on [accountId]'s balance*, expressed in [currency]:
 * - [TransactionType.EXPENSE]: negative
 * - [TransactionType.INCOME]: positive
 * - [TransactionType.ADJUSTMENT]: signed delta (either direction)
 * - [TransactionType.TRANSFER]: negative (funds leave the source account)
 *
 * ### Transfers
 * A transfer is a single record (PLANNING ADR 2). [accountId] is the source and
 * [transferAccountId] the destination. [transferAmount] is the positive effect on
 * the destination in [transferCurrency]; for same-currency transfers it equals
 * `-amount`. Different currencies (the user types both legs) are supported by the
 * separate destination amount/currency.
 *
 * A movement's [currency] is assumed to match its [accountId]'s currency, so
 * per-account balances never mix currencies.
 */
data class Transaction(
    val type: TransactionType,
    val amount: BigDecimal,
    val currency: Currency,
    val accountId: Long,
    val timestamp: Instant,
    val zoneOffset: ZoneOffset,
    val id: Long = 0L,
    val transferAccountId: Long? = null,
    val transferAmount: BigDecimal? = null,
    val transferCurrency: Currency? = null,
    val categoryId: Long? = null,
    val description: String? = null,
    val note: String? = null,
    val isExcludedFromStats: Boolean = false,
    val isRefund: Boolean = false,
    val recurringRuleId: Long? = null,
    /**
     * True for a recurring movement awaiting confirmation (confirm mode / variable
     * amount). Pending movements do not affect balances or statistics until confirmed.
     */
    val isPending: Boolean = false,
    /**
     * For generated recurring movements, the schedule occurrence this movement
     * materializes; null for manual movements. Identifies the occurrence even if
     * the user later edits the movement's date, and backs the unique constraint
     * that prevents double generation.
     */
    val recurringOccurrenceDate: LocalDate? = null,
    /**
     * The person this movement is a loan to or from (ADR 34): an expense with a
     * counterparty is money lent, an income with one is money returned or
     * received as a loan. Null on every ordinary movement. A movement carrying a
     * counterparty always has [isExcludedFromStats] on - lending is not
     * spending - while its effect on the account balance is that of any other
     * movement: the money really did leave the account.
     */
    val counterparty: String? = null,
    /**
     * Whether the user asked to be reminded before [timestamp] falls due
     * (ADR 36). Only offered while the date is in the future: a one-off
     * deadline becomes a dated movement with a reminder, instead of a yearly
     * recurring rule that does not describe it. The lead time is the one
     * configured for the pre-renewal radar, so there is a single answer to
     * "how early do you want to know".
     */
    val hasReminder: Boolean = false,
    /**
     * The movement date already reminded about, twin of
     * [RecurringRule.lastReminderDate]: it keeps a daily run inside the lead
     * window from notifying more than once. Null until the first reminder.
     */
    val lastReminderDate: LocalDate? = null,
)

/** The movement's own local day, from the offset stored with it (ADR 7). */
val Transaction.localDate: LocalDate get() = timestamp.atOffset(zoneOffset).toLocalDate()

/**
 * True when this movement was generated by a recurring rule (PLANNING ADR 4).
 * The link is cleared to null when the rule is deleted, so a former recurring
 * movement reads as manual afterwards.
 */
val Transaction.isRecurring: Boolean get() = recurringRuleId != null
