package com.callbackdev.saldo.core.domain.model

import java.math.BigDecimal
import java.time.LocalDate
import java.util.Currency

/**
 * Where an upcoming movement comes from. The distinction is visible in the list
 * because it changes what the user can do with it: a pending occurrence is
 * waiting for an answer, the other two are already decided.
 */
enum class UpcomingOrigin {
    /** Entered by hand with a future date: a deadline the user chose to record. */
    MANUAL,

    /** Generated by a recurring rule and confirmed, but dated ahead. */
    RECURRING,

    /** A generated occurrence still awaiting confirmation (confirm mode / variable amount). */
    PENDING,
}

/**
 * A movement that has not happened yet: either a confirmed one dated in the
 * future, or an occurrence still to confirm (ADR 36). Both already exist as
 * rows in the ledger - this is a reading of them, not a second register.
 *
 * [date] is the movement's own local day (ADR 7) for a confirmed movement and
 * the occurrence's day for a pending one, which is what "when it is due" means
 * in each case.
 */
data class UpcomingMovement(
    val transaction: Transaction,
    val date: LocalDate,
    val origin: UpcomingOrigin,
) {
    val id: Long get() = transaction.id

    val isPending: Boolean get() = origin == UpcomingOrigin.PENDING

    /**
     * Signed effect on the source account, the figure the row shows: negative
     * for an expense or the outgoing leg of a transfer, positive for an income.
     */
    val amount: BigDecimal get() = transaction.amount
}

/**
 * The "Upcoming" list and the two totals that head it, in the primary currency.
 *
 * The totals stay separate, like the credits and debts ones: 300 going out and
 * 300 coming in is not "nothing is going to happen", and a single net figure
 * would say exactly that. Transfers are in neither: money moving between one's
 * own accounts is not something coming in or going out (ADR 8's reasoning
 * applied to a forward-looking list).
 */
data class UpcomingLedger(
    val items: List<UpcomingMovement> = emptyList(),
    /** Positive magnitude of the expenses ahead, in [currency]. */
    val outgoing: BigDecimal = BigDecimal.ZERO,
    /** Positive magnitude of the incomes ahead, in [currency]. */
    val incoming: BigDecimal = BigDecimal.ZERO,
    val currency: Currency = fallbackCurrency,
    /** How many of [items] are waiting for a confirmation. */
    val pendingCount: Int = 0,
    /**
     * True when a movement in another currency stays out of the totals: every
     * foreign movement with conversion off, only the ones without a usable
     * rate with it on (ADR 40). The totals would otherwise under-report in
     * silence (the same notice the statistics carry since Phase 10.16).
     */
    val hasOtherCurrencies: Boolean = false,
    /**
     * True when the totals include foreign movements converted at the rate of
     * their own (future) day, i.e. the latest known one (ADR 40): the figures
     * are estimates and the UI declares it.
     */
    val includesEstimates: Boolean = false,
) {
    val isEmpty: Boolean get() = items.isEmpty()
}
