package com.callbackdev.saldo.feature.transactions

import com.callbackdev.saldo.core.common.money.MoneyInput
import com.callbackdev.saldo.core.domain.model.Account
import com.callbackdev.saldo.core.domain.model.AccountWithBalance
import com.callbackdev.saldo.core.domain.model.Category
import com.callbackdev.saldo.core.domain.model.Tag
import com.callbackdev.saldo.core.domain.model.TransactionType
import com.callbackdev.saldo.core.domain.money.MoneyMapper
import java.math.BigDecimal
import java.math.RoundingMode
import java.time.LocalDate
import java.time.LocalTime
import java.util.Currency

/** Immutable UI state of the transaction editor form. */
data class TransactionEditorUiState(
    val isLoading: Boolean = true,
    val isNew: Boolean = true,
    val type: TransactionType = TransactionType.EXPENSE,
    /** True when editing a transfer or an adjustment: the type cannot change. */
    val isTypeLocked: Boolean = false,
    /** True when the type was chosen upfront (quick action): no in-form type selector. */
    val isTypePreset: Boolean = false,
    val amountInput: String = "",
    val toAmountInput: String = "",
    /** Accounts offered by the pickers: active ones plus any referenced archived one. */
    val accounts: List<AccountWithBalance> = emptyList(),
    val account: Account? = null,
    val toAccount: Account? = null,
    /** Categories usable for the current type (expense set when a refund). */
    val categories: List<Category> = emptyList(),
    val categoryId: Long? = null,
    val date: LocalDate = LocalDate.ofEpochDay(0),
    val time: LocalTime = LocalTime.MIDNIGHT,
    val description: String = "",
    /** The long free-text note; blank means none. */
    val note: String = "",
    val allTags: List<Tag> = emptyList(),
    val selectedTags: List<Tag> = emptyList(),
    val isExcludedFromStats: Boolean = false,
    val isRefund: Boolean = false,
    /** True when the movement is marked as a loan to or from a person (ADR 34). */
    val isCounterparty: Boolean = false,
    /** The person's name while [isCounterparty] is on; blank until typed. */
    val counterparty: String = "",
    /** Names already used, matching what is typed so far, for one-tap completion. */
    val counterpartySuggestions: List<String> = emptyList(),
    /**
     * Whether the user asked to be reminded before this movement falls due
     * (ADR 36). Only meaningful while [isFutureDated]; the editor hides the
     * switch otherwise rather than offering a promise it cannot keep.
     */
    val hasReminder: Boolean = false,
    /** Today, to tell a future-dated movement from a past one. */
    val today: LocalDate = LocalDate.ofEpochDay(0),
    /** True when the movement being edited was generated by a recurring rule. */
    val isRecurring: Boolean = false,
    /** Name of the generating rule, when it could be resolved; for the banner. */
    val recurringRuleName: String? = null,
    /**
     * True when this new movement was prefilled from another one whose account
     * is archived (Fase 39, F2): the default account took its place and the
     * banner says so, since the copy is not quite the original.
     */
    val duplicateAccountReplaced: Boolean = false,
    /** Set on a failed save attempt to surface field errors. */
    val showValidation: Boolean = false,
) {
    val currency: Currency? get() = account?.currency

    /**
     * True when the movement is dated ahead: it belongs to the ledger and to
     * the balance, but to nothing scoped to today, and it is the only case
     * where a reminder has anything to remind about.
     */
    val isFutureDated: Boolean get() = date > today

    /**
     * Whether the reminder switch is offered. Adjustments are excluded: a
     * balance restatement dated ahead is a correction waiting to apply, not an
     * appointment to keep.
     */
    val hasReminderSection: Boolean
        get() = isFutureDated && type != TransactionType.ADJUSTMENT

    /** Decimals the two amount inputs accept, from their own account's currency. */
    val amountFractionDigits: Int
        get() = currency?.let(MoneyMapper::fractionDigits) ?: DEFAULT_FRACTION_DIGITS

    val toAmountFractionDigits: Int
        get() = toAccount?.currency?.let(MoneyMapper::fractionDigits) ?: DEFAULT_FRACTION_DIGITS

    /** Only a balance adjustment can be negative: it restates a balance, up or down. */
    val allowsNegativeAmount: Boolean get() = type == TransactionType.ADJUSTMENT

    val isTransfer: Boolean get() = type == TransactionType.TRANSFER

    /** True when both transfer legs are chosen and their currencies differ. */
    val isCrossCurrency: Boolean
        get() = isTransfer && account != null && toAccount != null &&
            account.currency != toAccount.currency

    val hasCategorySection: Boolean
        get() = type == TransactionType.EXPENSE || type == TransactionType.INCOME

    val isAmountValid: Boolean
        get() = MoneyInput.parse(amountInput)?.let { amount ->
            if (type == TransactionType.ADJUSTMENT) amount.signum() != 0 else amount.signum() > 0
        } ?: false

    val isAccountValid: Boolean get() = account != null

    val isToAccountValid: Boolean
        get() = !isTransfer || (toAccount != null && toAccount.id != account?.id)

    val isToAmountValid: Boolean
        get() = !isCrossCurrency || (MoneyInput.parse(toAmountInput)?.signum() ?: 0) > 0

    val isCategoryValid: Boolean get() = !hasCategorySection || categoryId != null

    /**
     * A loan needs a name: without one the movement would sit outside the
     * statistics and outside the credits and debts screen too, visible nowhere.
     */
    val isCounterpartyValid: Boolean
        get() = !hasCategorySection || !isCounterparty || counterparty.isNotBlank()

    val isValid: Boolean
        get() = isAmountValid && isAccountValid && isToAccountValid &&
            isToAmountValid && isCategoryValid && isCounterpartyValid

    /** Rate implied by the two legs of a cross-currency transfer, or null. */
    val impliedRate: BigDecimal?
        get() = if (isCrossCurrency) impliedExchangeRate(amountInput, toAmountInput) else null
}

/**
 * Destination units per source unit implied by the two typed amounts of a
 * cross-currency transfer; null until both parse to a non-zero value. A local
 * plausibility check, never persisted.
 */
internal fun impliedExchangeRate(sentInput: String, receivedInput: String): BigDecimal? {
    val sent = MoneyInput.parse(sentInput)?.abs() ?: return null
    val received = MoneyInput.parse(receivedInput)?.abs() ?: return null
    if (sent.signum() == 0 || received.signum() == 0) return null
    return received.divide(sent, IMPLIED_RATE_SCALE, RoundingMode.HALF_UP)
}

private const val IMPLIED_RATE_SCALE = 4

/** Decimals assumed while no account (hence no currency) is chosen yet. */
internal const val DEFAULT_FRACTION_DIGITS = 2

/** One-shot events consumed by the editor screen. */
sealed interface TransactionEditorEvent {
    data object Saved : TransactionEditorEvent

    data object Deleted : TransactionEditorEvent

    /** The transaction to edit no longer exists: leave the screen. */
    data object TransactionMissing : TransactionEditorEvent

    /** A write failed: stay on the screen and let the user retry. */
    data object WriteFailed : TransactionEditorEvent
}
