package com.callbackdev.saldo.core.domain.usecase

import com.callbackdev.saldo.core.domain.model.TransactionType
import com.callbackdev.saldo.core.domain.recurrence.CandidateOccurrence
import com.callbackdev.saldo.core.domain.recurrence.RecurrenceAmountGroup
import com.callbackdev.saldo.core.domain.recurrence.RecurrenceCandidateGroup
import com.callbackdev.saldo.core.domain.recurrence.RecurrenceDescriptionGroup
import com.callbackdev.saldo.core.domain.recurrence.RecurrenceDetector
import com.callbackdev.saldo.core.domain.recurrence.RecurrenceScanResult
import com.callbackdev.saldo.core.domain.recurrence.RecurrenceSuggestion
import com.callbackdev.saldo.core.domain.repository.TransactionRepository
import com.callbackdev.saldo.core.domain.search.SearchText
import java.time.Clock
import java.time.Instant
import java.time.LocalDate
import java.util.Currency
import javax.inject.Inject

/**
 * The recurrence scan (Fase 19, ADR 43): finds regular series among confirmed
 * movements not generated by a rule and proposes them as suggestions. Runs
 * ONLY when the user taps the hub row: no worker, no observer, nothing on hub
 * open. Real domain logic (two candidate paths, merge, dedup, ranking), so a
 * use case per ADR 12.
 *
 * Every cap is declared and the result says when one cut something
 * ([RecurrenceScanResult.truncated]): a silent cap does not exist. The cost
 * ceiling per scan is two aggregate queries plus at most
 * 2 x [MAX_CANDIDATE_GROUPS] capped point reads on the candidate groups,
 * independent of the ledger size.
 */
class DetectRecurrenceSuggestionsUseCase @Inject constructor(
    private val transactionRepository: TransactionRepository,
    private val clock: Clock,
) {

    suspend operator fun invoke(today: LocalDate = LocalDate.now(clock)): RecurrenceScanResult {
        val since = today.minusMonths(WINDOW_MONTHS).atStartOfDay(clock.zone).toInstant()
        val minCount = RecurrenceDetector.MIN_OCCURRENCES
        // One extra row per query is the truncation probe: LIMIT alone cannot say "there was more".
        val descriptionGroups =
            transactionRepository.recurrenceDescriptionGroups(since, minCount, MAX_CANDIDATE_GROUPS + 1)
        val amountGroups =
            transactionRepository.recurrenceAmountGroups(since, minCount, MAX_CANDIDATE_GROUPS + 1)
        var truncated = descriptionGroups.size > MAX_CANDIDATE_GROUPS ||
            amountGroups.size > MAX_CANDIDATE_GROUPS

        // Description-keyed series first: they carry a name and survive amount changes,
        // so they win over their own amount-keyed duplicates.
        val fromDescriptions = detectFromDescriptions(
            descriptionGroups.take(MAX_CANDIDATE_GROUPS),
            since,
            today,
        )
        val fromAmounts = detectFromAmounts(amountGroups.take(MAX_CANDIDATE_GROUPS), since, today)
            .filter { candidate ->
                fromDescriptions.none { RecurrenceDetector.duplicates(it, candidate) }
            }

        val ranked = (fromDescriptions + fromAmounts)
            .sortedWith(
                compareByDescending<RecurrenceSuggestion> { it.occurrenceCount }
                    .thenByDescending { it.lastOccurrence }
                    .thenBy { it.key },
            )
        if (ranked.size > MAX_SUGGESTIONS) truncated = true
        return RecurrenceScanResult(ranked.take(MAX_SUGGESTIONS), truncated)
    }

    /**
     * The variable-bill path. SQL groups by ASCII-folded description; groups
     * that collapse under the real search normalization ("Créd" vs "cred")
     * are merged here before detection, so an accent never splits a series.
     */
    private suspend fun detectFromDescriptions(
        groups: List<RecurrenceDescriptionGroup>,
        since: Instant,
        today: LocalDate,
    ): List<RecurrenceSuggestion> = groups
        .groupBy { group ->
            SeriesKey(
                type = group.type,
                accountId = group.accountId,
                categoryId = group.categoryId,
                currency = group.currency,
                discriminator = SearchText.normalize(group.descriptionKey),
            )
        }
        .mapNotNull { (key, sameSeries) ->
            val occurrences = sameSeries.flatMap { group ->
                transactionRepository.recurrenceDescriptionGroupOccurrences(
                    group,
                    since,
                    MAX_ROWS_PER_GROUP,
                )
            }
            detect(key, prefix = "desc", occurrences, today)
        }

    /** The fixed-price path: subscriptions, with or without a description. */
    private suspend fun detectFromAmounts(
        groups: List<RecurrenceAmountGroup>,
        since: Instant,
        today: LocalDate,
    ): List<RecurrenceSuggestion> = groups.mapNotNull { group ->
        val occurrences = transactionRepository.recurrenceAmountGroupOccurrences(
            group,
            since,
            MAX_ROWS_PER_GROUP,
        )
        val key = SeriesKey(
            type = group.type,
            accountId = group.accountId,
            categoryId = group.categoryId,
            currency = group.currency,
            discriminator = group.amountMinor.toString(),
        )
        detect(key, prefix = "amount", occurrences, today)
    }

    private fun detect(
        key: SeriesKey,
        prefix: String,
        occurrences: List<CandidateOccurrence>,
        today: LocalDate,
    ): RecurrenceSuggestion? {
        val group = RecurrenceCandidateGroup(
            stableKey = key.stableKey(prefix),
            type = key.type,
            accountId = key.accountId,
            categoryId = key.categoryId,
            currency = key.currency,
            displayName = displayName(occurrences),
            occurrences = occurrences,
        )
        return RecurrenceDetector.detect(group, today)
    }

    /** The most frequent raw description of the series, spelling and casing as the user wrote it. */
    private fun displayName(occurrences: List<CandidateOccurrence>): String? = occurrences
        .mapNotNull { it.description?.trim() }
        .filter { it.isNotEmpty() }
        .groupingBy { it }
        .eachCount()
        .maxByOrNull { it.value }
        ?.key

    /** Identity of a series, shared by the merge, the stable dismiss key and the dedup. */
    private data class SeriesKey(
        val type: TransactionType,
        val accountId: Long,
        val categoryId: Long?,
        val currency: Currency,
        val discriminator: String,
    ) {
        fun stableKey(prefix: String): String =
            "$prefix:${type.name}:$accountId:${categoryId ?: "none"}:${currency.currencyCode}:$discriminator"
    }

    companion object {
        /** Declared caps of the phase: window, examined groups (per path), rows per group, shown suggestions. */
        const val WINDOW_MONTHS = 12L
        const val MAX_CANDIDATE_GROUPS = 25
        const val MAX_ROWS_PER_GROUP = 60
        const val MAX_SUGGESTIONS = 5
    }
}
