package com.callbackdev.saldo.core.database

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.callbackdev.saldo.core.database.dao.AccountDao
import com.callbackdev.saldo.core.database.dao.CategoryDao
import com.callbackdev.saldo.core.database.dao.RecurrenceCandidateDao
import com.callbackdev.saldo.core.database.dao.RecurringRuleDao
import com.callbackdev.saldo.core.database.dao.TransactionDao
import com.callbackdev.saldo.core.database.entity.AccountEntity
import com.callbackdev.saldo.core.database.entity.CategoryEntity
import com.callbackdev.saldo.core.database.entity.RecurringRuleEntity
import com.callbackdev.saldo.core.database.entity.TransactionEntity
import com.callbackdev.saldo.core.domain.model.AccountType
import com.callbackdev.saldo.core.domain.model.CategoryType
import com.callbackdev.saldo.core.domain.model.RecurrenceFrequency
import com.callbackdev.saldo.core.domain.model.TransactionType
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The candidate queries of the recurrence scan ([RecurrenceCandidateDao],
 * Fase 19, ADR 43): selection happens in SQL with declared caps, on confirmed
 * movements not generated by a rule and not excluded from statistics. These
 * tests pin the WHERE clause promises at the query level, like
 * [TransactionDaoUpcomingTest] does.
 */
@RunWith(AndroidJUnit4::class)
class TransactionDaoRecurrenceCandidatesTest {

    private lateinit var database: SaldoDatabase
    private lateinit var transactionDao: TransactionDao
    private lateinit var recurrenceCandidateDao: RecurrenceCandidateDao
    private lateinit var accountDao: AccountDao
    private lateinit var categoryDao: CategoryDao
    private lateinit var recurringRuleDao: RecurringRuleDao

    private var accountId = 0L
    private var subscriptions = 0L
    private var ruleId = 0L

    private val now = 1_800_000_000_000L
    private val day = 86_400_000L
    private val month = 30 * day
    private val windowStart = now - 365 * day

    @Before
    fun setUp() {
        val context = ApplicationProvider.getApplicationContext<android.content.Context>()
        database = Room.inMemoryDatabaseBuilder(context, SaldoDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        transactionDao = database.transactionDao()
        recurrenceCandidateDao = database.recurrenceCandidateDao()
        accountDao = database.accountDao()
        categoryDao = database.categoryDao()
        recurringRuleDao = database.recurringRuleDao()
        runBlocking {
            accountId = accountDao.insert(
                AccountEntity(
                    name = "Checking",
                    type = AccountType.CHECKING,
                    currency = "EUR",
                    initialBalanceMinor = 0L,
                ),
            )
            subscriptions = categoryDao.insert(
                CategoryEntity(
                    name = "Subscriptions",
                    type = CategoryType.EXPENSE,
                    color = 0x66BB6A,
                    icon = "subscriptions",
                ),
            )
            ruleId = recurringRuleDao.insert(
                RecurringRuleEntity(
                    name = "Netflix",
                    type = TransactionType.EXPENSE,
                    currency = "EUR",
                    accountId = accountId,
                    frequency = RecurrenceFrequency.MONTHLY,
                    startDateEpochDay = 20_000L,
                    amountMinor = -1_299L,
                ),
            )
        }
    }

    @After
    fun tearDown() {
        database.close()
    }

    @Suppress("LongParameterList")
    private fun movement(
        amountMinor: Long,
        atMillis: Long,
        description: String? = null,
        type: TransactionType = TransactionType.EXPENSE,
        isPending: Boolean = false,
        excludedFromStats: Boolean = false,
        recurringRuleId: Long? = null,
    ) = TransactionEntity(
        type = type,
        amountMinor = amountMinor,
        currency = "EUR",
        accountId = accountId,
        timestampEpochMilli = atMillis,
        zoneOffsetSeconds = 7200,
        categoryId = subscriptions,
        description = description,
        isPending = isPending,
        isExcludedFromStats = excludedFromStats,
        recurringRuleId = recurringRuleId,
    )

    private suspend fun amountGroups(minCount: Int = 3, limit: Int = 25) =
        recurrenceCandidateDao.recurrenceAmountGroups(windowStart, minCount, limit)

    private suspend fun descriptionGroups(minCount: Int = 3, limit: Int = 25) =
        recurrenceCandidateDao.recurrenceDescriptionGroups(windowStart, minCount, limit)

    @Test
    fun groupsByExactAmountWithTheMinimumCount() = runBlocking {
        repeat(3) { transactionDao.insert(movement(-1_299L, now - it * month)) }
        repeat(2) { transactionDao.insert(movement(-999L, now - it * month)) }

        val groups = amountGroups()

        // Only the three-strong group qualifies; two occurrences are noise.
        assertEquals(1, groups.size)
        assertEquals(-1_299L, groups.single().amountMinor)
        assertEquals(3, groups.single().count)
    }

    @Test
    fun excludesRuleGeneratedPendingExcludedAndOldMovements() = runBlocking {
        // Three of each polluting kind: none may form a group.
        repeat(3) { transactionDao.insert(movement(-1_299L, now - it * month, recurringRuleId = ruleId)) }
        repeat(3) { transactionDao.insert(movement(-999L, now - it * month, isPending = true)) }
        repeat(3) { transactionDao.insert(movement(-777L, now - it * month, excludedFromStats = true)) }
        repeat(3) { transactionDao.insert(movement(-555L, windowStart - (it + 1) * month)) }

        assertTrue(amountGroups().isEmpty())
        assertTrue(descriptionGroups().isEmpty())
    }

    @Test
    fun excludesTransfersAndAdjustmentsByType() = runBlocking {
        repeat(3) { transactionDao.insert(movement(-2_000L, now - it * month, type = TransactionType.ADJUSTMENT)) }

        assertTrue(amountGroups().isEmpty())
    }

    @Test
    fun respectsTheDeclaredGroupCap() = runBlocking {
        repeat(4) { group ->
            repeat(3) { transactionDao.insert(movement(-100L * (group + 1), now - it * month)) }
        }

        assertEquals(2, amountGroups(limit = 2).size)
    }

    @Test
    fun groupsDescriptionsCaseInsensitivelyAndTrimmed() = runBlocking {
        transactionDao.insert(movement(-4_200L, now - 2 * month, description = "Enel Energia"))
        transactionDao.insert(movement(-4_500L, now - month, description = "  enel energia "))
        transactionDao.insert(movement(-4_700L, now, description = "ENEL ENERGIA"))

        val groups = descriptionGroups()

        assertEquals(1, groups.size)
        assertEquals("enel energia", groups.single().descriptionKey)
        assertEquals(3, groups.single().count)
    }

    @Test
    fun blankDescriptionsNeverFormAGroup() = runBlocking {
        repeat(3) { transactionDao.insert(movement(-4_200L + it, now - it * month, description = "   ")) }
        repeat(3) { transactionDao.insert(movement(-5_000L + it, now - it * month, description = null)) }

        assertTrue(descriptionGroups().isEmpty())
    }

    @Test
    fun fetchesTheOccurrencesOfOneAmountGroupOnly() = runBlocking {
        repeat(3) { transactionDao.insert(movement(-1_299L, now - it * month, description = "Netflix")) }
        repeat(3) { transactionDao.insert(movement(-999L, now - it * month)) }

        val group = amountGroups().first { it.amountMinor == -1_299L }
        val rows = recurrenceCandidateDao.recurrenceAmountGroupOccurrences(
            type = group.type,
            accountId = group.accountId,
            categoryId = group.categoryId,
            currency = group.currency,
            amountMinor = group.amountMinor,
            sinceMillis = windowStart,
            limit = 60,
        )

        assertEquals(3, rows.size)
        assertTrue(rows.all { it.amountMinor == -1_299L })
        assertTrue(rows.all { it.description == "Netflix" })
    }

    @Test
    fun fetchesTheOccurrencesOfOneDescriptionGroupAcrossAmounts() = runBlocking {
        transactionDao.insert(movement(-4_200L, now - 2 * month, description = "Enel Energia"))
        transactionDao.insert(movement(-4_500L, now - month, description = "enel energia"))
        transactionDao.insert(movement(-4_700L, now, description = "ENEL ENERGIA"))
        transactionDao.insert(movement(-999L, now, description = "Bar"))

        val group = descriptionGroups().single()
        val rows = recurrenceCandidateDao.recurrenceDescriptionGroupOccurrences(
            type = group.type,
            accountId = group.accountId,
            categoryId = group.categoryId,
            currency = group.currency,
            descriptionKey = group.descriptionKey,
            sinceMillis = windowStart,
            limit = 60,
        )

        assertEquals(3, rows.size)
        assertEquals(listOf(-4_700L, -4_500L, -4_200L), rows.map { it.amountMinor })
    }

    @Test
    fun comesBackEmptyOnAFreshInstall() = runBlocking {
        assertTrue(amountGroups().isEmpty())
        assertTrue(descriptionGroups().isEmpty())
    }
}
