package com.callbackdev.saldo.core.database.dao

import androidx.room.Dao
import androidx.room.Query
import com.callbackdev.saldo.core.database.relation.RecurrenceAmountGroupRow
import com.callbackdev.saldo.core.database.relation.RecurrenceDescriptionGroupRow
import com.callbackdev.saldo.core.database.relation.RecurrenceOccurrenceRow

/**
 * Candidate queries of the recurrence scan (Fase 19, ADR 43). Selection
 * happens here in SQL so the scan cost stays flat as the ledger grows: the
 * detector only ever sees these few groups, never the ledger. Their own DAO
 * rather than more rows in [TransactionDao], like [ForeignFlowDao]: the
 * family is cohesive (it exists only for the scan) and nothing else ever
 * runs it - these queries execute ONLY on the explicit user action in the
 * hub, never on open and never from an observer.
 *
 * Shared filters: confirmed movements only, not generated by a rule,
 * expenses and incomes only (transfers and adjustments are types), and not
 * excluded from statistics - a loan to a person (ADR 34) or a deliberately
 * excluded movement is not representable by a rule, which always generates
 * plain statistical movements.
 */
@Dao
interface RecurrenceCandidateDao {

    /**
     * Candidate groups keyed by exact amount: confirmed movements grouped by
     * type, account, category, currency and amount. The fixed-price path
     * (subscriptions, with or without a description).
     */
    @Query(
        """
        SELECT type AS type, accountId AS accountId, categoryId AS categoryId,
            currency AS currency, amountMinor AS amountMinor, COUNT(*) AS count
        FROM transactions
        WHERE type IN ('EXPENSE', 'INCOME')
            AND isPending = 0
            AND recurringRuleId IS NULL
            AND isExcludedFromStats = 0
            AND timestampEpochMilli >= :sinceMillis
        GROUP BY type, accountId, categoryId, currency, amountMinor
        HAVING COUNT(*) >= :minCount
        ORDER BY count DESC, MAX(timestampEpochMilli) DESC
        LIMIT :limit
        """,
    )
    suspend fun recurrenceAmountGroups(
        sinceMillis: Long,
        minCount: Int,
        limit: Int,
    ): List<RecurrenceAmountGroupRow>

    /**
     * Candidate groups keyed by case-folded description: the variable-bill
     * path, where the amount changes but the description repeats. `LOWER`
     * folds ASCII only, like the `LIKE` prefilter of
     * [TransactionDao.descriptionUsage]: the accent-insensitive merge happens
     * in Kotlin on these few groups.
     */
    @Query(
        """
        SELECT type AS type, accountId AS accountId, categoryId AS categoryId,
            currency AS currency, LOWER(TRIM(description)) AS descriptionKey, COUNT(*) AS count
        FROM transactions
        WHERE type IN ('EXPENSE', 'INCOME')
            AND isPending = 0
            AND recurringRuleId IS NULL
            AND isExcludedFromStats = 0
            AND description IS NOT NULL AND TRIM(description) <> ''
            AND timestampEpochMilli >= :sinceMillis
        GROUP BY type, accountId, categoryId, currency, descriptionKey
        HAVING COUNT(*) >= :minCount
        ORDER BY count DESC, MAX(timestampEpochMilli) DESC
        LIMIT :limit
        """,
    )
    suspend fun recurrenceDescriptionGroups(
        sinceMillis: Long,
        minCount: Int,
        limit: Int,
    ): List<RecurrenceDescriptionGroupRow>

    /**
     * The movements of one amount-keyed candidate group, most recent first and
     * capped, so a pathological group cannot make the scan read the ledger.
     * The nullable category comparison is spelled out because SQL `=` never
     * matches NULL.
     */
    @Query(
        """
        SELECT (timestampEpochMilli / 1000 + zoneOffsetSeconds) / 86400 AS epochDay,
            amountMinor AS amountMinor, description AS description
        FROM transactions
        WHERE type = :type
            AND accountId = :accountId
            AND ((:categoryId IS NULL AND categoryId IS NULL) OR categoryId = :categoryId)
            AND currency = :currency
            AND amountMinor = :amountMinor
            AND isPending = 0
            AND recurringRuleId IS NULL
            AND isExcludedFromStats = 0
            AND timestampEpochMilli >= :sinceMillis
        ORDER BY timestampEpochMilli DESC
        LIMIT :limit
        """,
    )
    @Suppress("LongParameterList") // One bind per group-key column; a DAO cannot take a POJO.
    suspend fun recurrenceAmountGroupOccurrences(
        type: String,
        accountId: Long,
        categoryId: Long?,
        currency: String,
        amountMinor: Long,
        sinceMillis: Long,
        limit: Int,
    ): List<RecurrenceOccurrenceRow>

    /** The movements of one description-keyed candidate group; twin of [recurrenceAmountGroupOccurrences]. */
    @Query(
        """
        SELECT (timestampEpochMilli / 1000 + zoneOffsetSeconds) / 86400 AS epochDay,
            amountMinor AS amountMinor, description AS description
        FROM transactions
        WHERE type = :type
            AND accountId = :accountId
            AND ((:categoryId IS NULL AND categoryId IS NULL) OR categoryId = :categoryId)
            AND currency = :currency
            AND description IS NOT NULL AND LOWER(TRIM(description)) = :descriptionKey
            AND isPending = 0
            AND recurringRuleId IS NULL
            AND isExcludedFromStats = 0
            AND timestampEpochMilli >= :sinceMillis
        ORDER BY timestampEpochMilli DESC
        LIMIT :limit
        """,
    )
    @Suppress("LongParameterList") // One bind per group-key column; a DAO cannot take a POJO.
    suspend fun recurrenceDescriptionGroupOccurrences(
        type: String,
        accountId: Long,
        categoryId: Long?,
        currency: String,
        descriptionKey: String,
        sinceMillis: Long,
        limit: Int,
    ): List<RecurrenceOccurrenceRow>
}
